#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk-direct-ip-remote-support/rustdesk /usr/bin/rustdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/rustdesk-direct-ip-remote-support.service ]; then
			rm /etc/systemd/system/rustdesk-direct-ip-remote-support.service /usr/lib/systemd/system/rustdesk-direct-ip-remote-support.service /usr/lib/systemd/user/rustdesk-direct-ip-remote-support.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk-direct-ip-remote-support/files/systemd/rustdesk-direct-ip-remote-support.service /usr/lib/systemd/system/rustdesk-direct-ip-remote-support.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk-direct-ip-remote-support.service: Unit rustdesk-direct-ip-remote-support.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk-direct-ip-remote-support.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/rustdesk-direct-ip-remote-support.service
		fi
		systemctl daemon-reload
		systemctl enable rustdesk-direct-ip-remote-support
		systemctl start rustdesk-direct-ip-remote-support
	fi
fi
